name: Run API Tests with Allure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:   # <-- Add this line for manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v2
        with:
          gradle-version: '8.0'

      - name: Execute tests (even if failed)
        run: |
          ./gradlew clean test || echo "Tests failed, but continuing to generate report..."

      - name: Generate Allure Report
        run: |
          ./gradlew allureReport

      - name: Zip Allure Report
        run: |
          zip -r allure-report.zip build/reports/allure-report

      - name: Upload Allure Report ZIP
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report.zip

      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        if: always() # upload even on failure
        with:
          name: test-results
          path: build/test-results/test/*.xml

      - name: Publish test results with GitHub Checks
        uses: dorny/test-reporter@v1
        if: always() # publish even on failure
        with:
          name: JUnit Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
