name: Run API Tests with Allure

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pages: write
  id-token: write  # required for GitHub Pages deployment

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Execute tests (even if failed)
        run: ./gradlew clean test || echo "Tests failed, but continuing to generate report..."

      - name: Generate Allure Report
        run: ./gradlew allureReport

      - name: Upload Allure Report for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/reports/allure-report/allureReport

      - name: Upload test results artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: build/reports/tests/test/**

      - name: Publish test results with GitHub Checks
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Test Report
          path: build/test-results/test/*.xml
          reporter: java-junit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/master'
    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
